-- rule = {
--     matches = {
--         {
--             { "node.name", "equals", "bluez_output.02_11_45_A0_B3_27.a2dp-sink" },
--         },
--     },
--     apply_properties = {
--         ["node.nick"] = "Headphones",
--     },
-- }

-- table.insert(bluez_monitor.rules, rule)